name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['published']

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
